//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChanPing
    {
        public int CPId { get; set; }
        public Nullable<int> JBId { get; set; }
        public Nullable<int> CKId { get; set; }
        public Nullable<int> CPSum { get; set; }
        public Nullable<int> COYuJing { get; set; }
        public string CPValue1 { get; set; }
        public string CPValue2 { get; set; }
    
        public virtual CangKu CangKu { get; set; }
        public virtual ChanPingJiBen ChanPingJiBen { get; set; }
    }
}
