//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChanPingJiBen
    {
        public ChanPingJiBen()
        {
            this.DingDangXX = new HashSet<DingDangXX>();
        }
    
        public int JBId { get; set; }
        public string JBNmae { get; set; }
        public string JBTeDian { get; set; }
        public Nullable<int> DWId { get; set; }
        public Nullable<int> CId { get; set; }
        public Nullable<decimal> jiage { get; set; }
        public string JBValue2 { get; set; }
    
        public virtual ChanPing ChanPing { get; set; }
        public virtual CPClass CPClass { get; set; }
        public virtual DanWei DanWei { get; set; }
        public virtual ICollection<DingDangXX> DingDangXX { get; set; }
    }
}
