//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DingDangXX
    {
        public int XXId { get; set; }
        public Nullable<int> DDId { get; set; }
        public Nullable<int> JBId { get; set; }
        public Nullable<int> Sum { get; set; }
        public string XXValue1 { get; set; }
        public string XXValue2 { get; set; }
    
        public virtual ChanPingJiBen ChanPingJiBen { get; set; }
        public virtual DingDan DingDan { get; set; }
    }
}
