//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logion
    {
        public Logion()
        {
            this.GeRenZiLiao = new HashSet<GeRenZiLiao>();
            this.ZHTypeJiLu = new HashSet<ZHTypeJiLu>();
        }
    
        public int ZHId { get; set; }
        public string ZhName { get; set; }
        public string ZHPwd { get; set; }
        public int JueSeId { get; set; }
        public Nullable<int> ZTId { get; set; }
        public string ZHValue1 { get; set; }
        public string ZHValue2 { get; set; }
    
        public virtual ICollection<GeRenZiLiao> GeRenZiLiao { get; set; }
        public virtual JueSe JueSe { get; set; }
        public virtual ZHType ZHType { get; set; }
        public virtual ICollection<ZHTypeJiLu> ZHTypeJiLu { get; set; }
    }
}
