//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHType
    {
        public ZHType()
        {
            this.Logion = new HashSet<Logion>();
            this.QianTaiYongHu = new HashSet<QianTaiYongHu>();
            this.ZHTypeJiLu = new HashSet<ZHTypeJiLu>();
        }
    
        public int ZTId { get; set; }
        public string ZTName { get; set; }
        public string JSValue1 { get; set; }
        public string JSValue2 { get; set; }
    
        public virtual ICollection<Logion> Logion { get; set; }
        public virtual ICollection<QianTaiYongHu> QianTaiYongHu { get; set; }
        public virtual ICollection<ZHTypeJiLu> ZHTypeJiLu { get; set; }
    }
}
