//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPClass
    {
        public CPClass()
        {
            this.ChanPingJiBen = new HashSet<ChanPingJiBen>();
        }
    
        public int CId { get; set; }
        public string CName { get; set; }
        public string CBeiZhu { get; set; }
        public string CValue1 { get; set; }
        public string CValue2 { get; set; }
    
        public virtual ICollection<ChanPingJiBen> ChanPingJiBen { get; set; }
    }
}
