//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DingDan
    {
        public DingDan()
        {
            this.DingDangXX = new HashSet<DingDangXX>();
        }
    
        public int DDId { get; set; }
        public Nullable<System.DateTime> DDTime { get; set; }
        public Nullable<int> DDType { get; set; }
        public Nullable<int> ZHId { get; set; }
        public string DDDiZhi { get; set; }
        public string DDValue1 { get; set; }
        public string DDValue2 { get; set; }
    
        public virtual ICollection<DingDangXX> DingDangXX { get; set; }
    }
}
