//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JueSe
    {
        public JueSe()
        {
            this.Logion = new HashSet<Logion>();
        }
    
        public int JueSeId { get; set; }
        public string JueSeName { get; set; }
        public Nullable<System.DateTime> JSTime { get; set; }
        public string JSBeiZhu { get; set; }
        public Nullable<int> JSzhuangtai { get; set; }
        public string JSValue2 { get; set; }
    
        public virtual ICollection<Logion> Logion { get; set; }
    }
}
